version: '3.4'

services:
  shoppinglist:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
    env_file:
      - environmentVariables.list
    ports:
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "@Rosen2000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080